---
version: 3
images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-supported-rhel8:latest
dependencies:
  ansible_core:
    package_pip: ansible-core>= 2.16.0
  ansible_runner:
    package_pip: ansible-runner
  galaxy:
    collections:
      - cohesity.dataprotect
  system:
    - pkgconf-pkg-config [platform:rpm]
    - systemd-devel [platform:rpm]
    - gcc [platform:rpm]
    - python39-devel [platform:rpm]
  python:
    - requests>=2.31.0
    - cohesity_management_sdk>=1.6.0

options:
  package_manager_path: /usr/bin/microdnf
